# Generated by Django 3.2.6 on 2021-08-28 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_surveyuseranswer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='title',
            new_name='surveyText',
        ),
        migrations.RenameField(
            model_name='surveyquestion',
            old_name='author',
            new_name='questionAuthor',
        ),
        migrations.RenameField(
            model_name='surveyquestion',
            old_name='question',
            new_name='questionText',
        ),
        migrations.RemoveField(
            model_name='surveyquestionalternative',
            name='question',
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='questionAlternatives',
            field=models.ManyToManyField(to='survey.SurveyQuestionAlternative'),
        ),
        migrations.AddField(
            model_name='surveyquestionalternative',
            name='questionAlternativeText',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
