# Generated by Django 3.2.6 on 2021-08-29 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_remove_surveyquestionalternative_rightalternative'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyuseranswer',
            old_name='questionQuestion',
            new_name='question',
        ),
    ]
