# Generated by Django 3.2.6 on 2021-08-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_rename_questionquestion_surveyuseranswer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='surveyQuestions',
        ),
        migrations.AddField(
            model_name='survey',
            name='surveyQuestionsx',
            field=models.ManyToManyField(to='survey.SurveyQuestion'),
        ),
    ]
