# Generated by Django 3.2.6 on 2021-08-29 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_auto_20210829_1018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='surveyQuestionsx',
            new_name='surveyQuestions',
        ),
    ]
