# Generated by Django 3.2.6 on 2021-08-29 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0010_rename_surveyquestionsx_survey_surveyquestions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='surveyQuestions',
        ),
        migrations.RemoveField(
            model_name='surveyquestion',
            name='questionAuthor',
        ),
        migrations.AddField(
            model_name='survey',
            name='questionAuthor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyquestion',
            name='survey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.survey'),
            preserve_default=False,
        ),
    ]
