# Generated by Django 3.2.6 on 2021-08-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0011_auto_20210829_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='questionAuthor',
            new_name='surveyAuthor',
        ),
    ]
